default: &default
  adapter: postgresql
  username: ENV["DB_USERNAME"]
  password: ENV["DB_PASSWORD"]
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ENV["DB_DEVELOPMENT"]
test:
  <<: *default
  database: ENV["DB_TEST"]

production:
  <<: *default
  database: ENV["DB_PRODUCTION"]
